[doit] general shell cleanup + fall back to wget2 if wget isn't present

diff --git a/doit b/doit
--- a/doit
+++ b/doit
@@ -13,7 +13,7 @@ GDBARGS=
 GDB=1
 GNU_MIRROR=https://mirrors.kernel.org/gnu
 # Get absolute path, will spawn a subshell then exit so our pwd is retained
-SCRIPTROOT=$(cd "$(dirname $0)" && pwd)
+SCRIPTROOT=$(cd "$(dirname "$0")" && pwd)
 PATCHES=$SCRIPTROOT/patches/
 
 # Cause errors in pipes to return failure when necessary
@@ -24,7 +24,7 @@ function err() {
     if [ "$QUIET" = "1" ]; then
         echo "doit: dumping last 50 lines of build log..."
         echo "doit: see $OUTDIR/build.log for the full details"
-        tail -50 $OUTDIR/build.log
+        tail -50 "$OUTDIR"/build.log
     fi
     exit 1
 }
@@ -54,9 +54,9 @@ function help()
 function log()
 {
     if [ "$QUIET" = "1" ]; then
-        "$@" >> $OUTDIR/build.log 2>&1
+        "$@" >> "$OUTDIR"/build.log 2>&1
     else
-        "$@" 2>&1 | tee -a $OUTDIR/build.log
+        "$@" 2>&1 | tee -a "$OUTDIR"/build.log
     fi
 }
 
@@ -71,7 +71,7 @@ function download-archive()
 
     if [ ! -f "$ARCHIVES/$filename" ]; then
        echo "fetching $name-$ver"
-       log wget -P "$ARCHIVES" -N "$GNU_MIRROR/$name/$subdir$filename"
+       log $WGET -P "$ARCHIVES" -N "$GNU_MIRROR/$name/$subdir$filename"
     else
        log echo "$filename already downloaded, skipping"
     fi
@@ -88,20 +88,20 @@ function extract-tool()
 {
     #echo "extract-tool" $1 $2 $3 $4 $5
 
-    local TARFILE=${1}-${2}.tar$3
-    local TARGETDIR=${1}-${2}
+    local TARFILE="${1}-${2}.tar$3"
+    local TARGETDIR="${1}-${2}"
     local HASH="$4"
 
-    if [ -z ${TARGETDIR} ]; then
+    if [ -z "$TARGETDIR" ]; then
         log echo "error, targetdir is empty"
         exit 1
     fi
 
-    if [ -f ${TARGETDIR}/.extracted ]; then
+    if [ -f "$TARGETDIR"/.extracted ]; then
         log echo "$TARFILE already extracted into $TARGETDIR, skipping"
         return 0
     fi
-    if [ ! -f $ARCHIVES/$TARFILE ]; then
+    if [ ! -f "$ARCHIVES/$TARFILE" ]; then
         log echo "error, missing $TARFILE"
         exit 1
     fi
@@ -113,12 +113,13 @@ function extract-tool()
     fi
 
     echo extracting $TARFILE
-    pushd $OUTDIR > /dev/null
+    pushd "$OUTDIR" > /dev/null || exit
     rm -rf -- "$TARGETDIR"
-    tar xf $ARCHIVES/$TARFILE || exit 1
+    tar xf "$ARCHIVES/$TARFILE" || exit 1
 
-    if [ ! -z "$5" ]; then
-        local PATCHES=$(echo $5-* | sort)
+    if [ -n "$5" ]; then
+        local PATCHES
+        PATCHES=$(echo "$5"-* | sort)
         for i in $PATCHES; do
             echo patching $1 with $i
             log echo patching $1 with $i
@@ -127,27 +128,38 @@ function extract-tool()
 
     fi
 
-    touch $TARGETDIR/.extracted || exit 1
-    popd > /dev/null
+    touch "$TARGETDIR"/.extracted || exit 1
+    popd > /dev/null || exit 1
 }
 
-MAKE=make
+MAKE="make"
 if [ "$OS" = "Linux" ]; then
-    COUNT=`grep processor /proc/cpuinfo | wc -l`
-    PARALLEL=-j`expr $COUNT + $COUNT`
+    COUNT=$(grep -c processor /proc/cpuinfo)
+    PARALLEL=-j$((COUNT + COUNT))
 fi
 if [ "$OS" = "Darwin" ]; then
-    PARALLEL=-j`sysctl -n hw.ncpu`
+    PARALLEL=-j$(sysctl -n hw.ncpu)
     export CXXFLAGS="-fbracket-depth=1024 -O2"
 fi
 if [ "$OS" = "FreeBSD" ]; then
-    PARALLEL=-j`sysctl -n hw.ncpu`
+    PARALLEL=-j$(sysctl -n hw.ncpu)
     export CXXFLAGS="-fbracket-depth=1024 -O2"
     MAKE=gmake
 fi
 
 if [ "$HOSTARCH" = "amd64" ]; then
     HOSTARCH=x86_64
+fi
+
+# if wget is not in the path, try to see if wget2 is in the path and set the WGET variable
+WGET=wget
+if [ -z "$(which $WGET)" ]; then
+    if [ -n "$(which wget2)" ]; then
+        WGET=wget2
+    else
+        echo "error: wget not found in PATH, please install wget or wget2"
+        exit 1
+    fi
 fi
 
 if [ $# == "0" ]; then
@@ -183,7 +195,7 @@ if [ -z "$ARCHES" ]; then
 fi
 
 if [ -z "$OUTDIR" ]; then
-    OUTDIR=`pwd`
+    OUTDIR=$(pwd)
 else
     if ! mkdir -p -- "$OUTDIR"; then
         log echo Unable to create output directory "$OUTDIR"
@@ -193,7 +205,7 @@ else
 fi
 ARCHIVES=$OUTDIR/archives
 
-if [ -z $(which makeinfo) ]; then
+if [ -z "$(which makeinfo)" ]; then
     echo makeinfo not found. On debian/ubuntu this is provided by the texinfo package.
     exit 1
 fi
@@ -209,7 +221,8 @@ fi
 log date
 log echo "ARCHES='$ARCHES' PARALLEL='$PARALLEL' FETCH='$FETCH' CCACHE='$CCACHE'"
 # load GCCVER and BINVER
-. toolvers
+# shellcheck source=toolvers
+source toolvers
 
 if [ "$FETCH" = "1" ]; then
     download-archive binutils $BINVER xz
@@ -220,7 +233,7 @@ if [ "$FETCH" = "1" ]; then
     download-archive mpfr $MPFRVER xz
 fi
 
-if [ ! -f $OUTDIR/.extracted-stamp ]; then
+if [ ! -f "$OUTDIR/.extracted-stamp" ]; then
     extract-tool binutils $BINVER .xz $BINHASH $PATCHES/binutils-patch
     extract-tool gcc $GCCVER .xz $GCCHASH $PATCHES/gcc-patch
     extract-tool gdb $GDBVER .xz $GDBHASH $PATCHES/gdb-patch
@@ -229,23 +242,23 @@ if [ ! -f $OUTDIR/.extracted-stamp ]; then
     extract-tool mpfr $MPFRVER .xz $MPFRHASH
 
     # link the last three libs into gcc
-    pushd $OUTDIR/gcc-$GCCVER > /dev/null
-    ln -sf ../gmp-$GMPVER gmp
-    ln -sf ../mpc-$MPCVER mpc
-    ln -sf ../mpfr-$MPFRVER mpfr
-    popd > /dev/null
+    pushd "$OUTDIR/gcc-$GCCVER" > /dev/null || exit 1
+    ln -sf "../gmp-$GMPVER" gmp
+    ln -sf "../mpc-$MPCVER" mpc
+    ln -sf "../mpfr-$MPFRVER" mpfr
+    popd > /dev/null || exit 1
 
     # link the last three libs into gdb
-    pushd $OUTDIR/gdb-$GDBVER > /dev/null
-    ln -sf ../gmp-$GMPVER gmp
-    ln -sf ../mpfr-$MPFRVER mpfr
-    popd > /dev/null
+    pushd "$OUTDIR/gdb-$GDBVER" > /dev/null || exit 1
+    ln -sf "../gmp-$GMPVER" gmp
+    ln -sf "../mpfr-$MPFRVER" mpfr
+    popd > /dev/null || exit 1
 
-    touch $OUTDIR/.extracted-stamp
+    touch "$OUTDIR/.extracted-stamp"
 fi
 
 # switch to the outdir to root all further activities
-pushd $OUTDIR > /dev/null
+pushd "$OUTDIR" > /dev/null || exit 1
 
 for ARCH in $ARCHES; do
     echo building for arch $ARCH
@@ -270,19 +283,19 @@ for ARCH in $ARCHES; do
     export PATH=$INSTALLPATH/bin:$PATH
 
     # Building Binutils
-    if [ ! -f $BINBUILDPATH/built.txt ]; then
+    if [ ! -f "$BINBUILDPATH/built.txt" ]; then
         echo building binutils
-        mkdir -p $BINBUILDPATH
-        pushd $BINBUILDPATH > /dev/null
-        log ../binutils-$BINVER/configure --target=$TARGET --prefix=$INSTALLPATH --disable-werror $BINUTILSARGS
-        log $MAKE $PARALLEL
+        mkdir -p "$BINBUILDPATH"
+        pushd "$BINBUILDPATH" > /dev/null || exit 1
+        log ../binutils-"$BINVER"/configure --target="$TARGET" --prefix="$INSTALLPATH" --disable-werror "$BINUTILSARGS"
+        log $MAKE "$PARALLEL"
         log $MAKE install
         touch built.txt
-        popd > /dev/null
+        popd > /dev/null || exit 1
     fi
 
     # Building GCC
-    if [ ! -f $GCCBUILDPATH/built.txt ]; then
+    if [ ! -f "$GCCBUILDPATH"/built.txt ]; then
         echo building gcc
         ARCH_OPTIONS=
         case "$TARGET" in
@@ -295,19 +308,19 @@ for ARCH in $ARCHES; do
                 ;;
         esac
 
-        mkdir -p $GCCBUILDPATH
-        pushd $GCCBUILDPATH > /dev/null
-        log ../gcc-$GCCVER/configure --target=$TARGET --prefix=$INSTALLPATH --enable-languages=c,c++ $ARCH_OPTIONS --disable-werror $GCCARGS
-        log $MAKE all-gcc $PARALLEL
-        log $MAKE all-target-libgcc $PARALLEL
+        mkdir -p "$GCCBUILDPATH"
+        pushd "$GCCBUILDPATH" > /dev/null || exit 1
+        log ../gcc-"$GCCVER"/configure --target="$TARGET" --prefix="$INSTALLPATH" --enable-languages=c,c++ "$ARCH_OPTIONS" --disable-werror "$GCCARGS"
+        log $MAKE all-gcc "$PARALLEL"
+        log $MAKE all-target-libgcc "$PARALLEL"
         log $MAKE install-gcc
         log $MAKE install-target-libgcc
         touch built.txt
-        popd > /dev/null
+        popd > /dev/null || exit 1
     fi
 
-    if (( $GDB )); then
-        if [ ! -f $GDBBUILDPATH/built.txt ]; then
+    if (( GDB )); then
+        if [ ! -f "$GDBBUILDPATH"/built.txt ]; then
             case "$TARGET" in
                 aarch64-elf) ARCH_OPTIONS="--enable-targets=arm-eabi --disable-sim" ;;
                 sparc-elf) ARCH_OPTIONS="--disable-sim" ;;
@@ -325,13 +338,13 @@ for ARCH in $ARCHES; do
             fi
 
             echo building gdb
-            mkdir -p $GDBBUILDPATH
-            pushd $GDBBUILDPATH > /dev/null
-            log ../gdb-$GDBVER/configure --target=$TARGET --prefix=$INSTALLPATH $ARCH_OPTIONS --disable-werror $GDBARGS
-            log $MAKE $PARALLEL
+            mkdir -p "$GDBBUILDPATH"
+            pushd "$GDBBUILDPATH" > /dev/null || exit 1
+            log ../gdb-"$GDBVER"/configure --target="$TARGET" --prefix="$INSTALLPATH" "$ARCH_OPTIONS" --disable-werror "$GDBARGS"
+            log $MAKE "$PARALLEL"
             log $MAKE install
             touch built.txt
-            popd > /dev/null
+            popd > /dev/null || exit 1
 
             export -n LDFLAGS
             export -n CPPFLAGS
@@ -347,6 +360,6 @@ for ARCH in $ARCHES; do
     fi
 done
 
-echo all done
+echo "all done"
 
 # vim: ts=4 sw=4 expandtab
